# Generated by Django 3.2.14 on 2022-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_images', models.ImageField(upload_to='upload_images')),
                ('text_1', models.CharField(blank=True, max_length=20, null=True)),
                ('text_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
